runtime: python39  
entrypoint: uvicorn api:app --host=0.0.0.0 --port=$PORT
instance_class: F4  # Choose an appropriate instance class

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1  # Minimum number of instances
  max_instances: 3  # Maximum number of instances
